insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'qualquer coisa no about', 'Brasilia', 'email@teste.com', 'senha123456', '55619876543', 'testetutor');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');

insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'qualquer coisa no about', 'Brasilia', 'email@teste.com', 'senha123456', '55619876543', 'testetutor');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');

insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'qualquer coisa no about', 'Brasilia', 'email@teste.com', 'senha123456', '55619876543', 'testetutor');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');
insert into tbl_tutor (id, txt_about, txt_city, txt_email, txt_password, txt_phone, txt_username) values (nextval('tbl_tutor_seq'), 'string', 'string', 'string', 'string', 'string', 'string');

insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo xpto','Sao paulo','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 22','Rio de Janeiro','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 38','Brasilia','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 41','Belo Horizonte','11123456789');
insert into tbl_abrigo (pk_long_id, txt_name, txt_city, txt_phone) values (nextval('tbl_abrigo_id_seq'), 'abrigo 56','Curitiba','11123456789');


insert into tbl_pet (pk_long_id, enum_specie, txt_city, txt_name, int_age, txt_personality, txt_size, fk_abrigo_id, bl_adotado) values (nextval('tbl_pet_seq'), 'Dog','Sao Paulo', 'caramelo', '5', 'docil e doido', 'medio', '1', false );